### ISSUE TITLE
How to debug ErrImagePull

### ISSUE THREAD

**Issue by v-lopez** [nabsul/k8s-ecr-login-renew#71]
I have been stuck for a week with this.

I have created a user with permissions to pull the image, let's say the details are:
ACCESS_KEY_ID=AKI1234
SECRET_ACCESS_KEY=SAK1234
REGION=eu-north-1
NAMESPACE=my_namespace

In my machine:
I can't pull the image by default.
I used `awscli` in my local machine to log in with those details.
Use `aws ecr --profile k8s-ecr-test get-login-password --region eu-north-1` to get password, and use it to login with ` docker login --username AWS --password ${SKYPILOT_DOCKER_PASSWORD} ${ECR_BASE}`.
Then I can pull the image.

On my k8s cluster, I use:
`helm install k8s-ecr-login-renew nabsul/k8s-ecr-login-renew --set awsRegion=eu-north-1,awsAccessKeyId=AKI1234,awsSecretAccessKey=SAK1234 -n my_namespace`

I then run manually the cron job:
`kubectl create job --from=cronjob/k8s-ecr-login-renew-cron k8s-ecr-login-renew-cron-manual-1 -n my_namespace`
And check the logs:

```
Running at 2025-02-24 13:41:32.970639356 +0000 UTC
Fetching auth data from AWS... Success.
Docker Registries: https://MY_ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com
Updating kubernetes secret [k8s-ecr-login-renew-docker-secret] in 1 namespaces
Updating secret in namespace [default]... success
Job complete.
```

Then `kubectl apply -f ` my job:
```
apiVersion: v1
kind: Pod
metadata:
  name: ecr-pull-test
  namespace: my_namespace
spec:
  containers:
    - name: test
      image: MY_ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/my_org/my-container:2025-02-04_13-30-31
      imagePullPolicy: Always
      command: ["sleep", "infinity"]  # Keeps the container running for debugging
  imagePullSecrets:
    - name: k8s-ecr-login-renew-docker-secret
```

But it gets stuck on:
```
kubectl get pods -n my_namespace
NAME                                                 READY   STATUS         RESTARTS   AGE
ecr-pull-test                                        0/1     ErrImagePull   0          54s
```

What am I doing wrong and how can I debug it?
