### ISSUE TITLE
Container stuck on `Running at...`

### ISSUE THREAD

**Issue by kuskoman** [nabsul/k8s-ecr-login-renew#8]
I am trying to use the project with following config:
```yaml
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: staging
  name: ecr-credentials-role
rules:
  - apiGroups: ["staging"]
    resources: ["secrets"]
    verbs: ["get", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-credentials-service
  namespace: staging
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ecr-credentials-role-binding
  namespace: staging
subjects:
  - kind: ServiceAccount
    name: ecr-credentials-service
    namespace: staging
roleRef:
  kind: Role
  name: ecr-credentials-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: staging
  name: cron-ecr-credentials-helper
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: ecr-credentials-service
          containers:
            - name: ecr-renew
              image: nabsul/k8s-ecr-login-renew:latest
              imagePullPolicy: "IfNotPresent"
              env:
                - name: DOCKER_SECRET_NAME
                  value: eu-west-1-ecr-registry
                - name: TARGET_NAMESPACE
                  value: staging
                - name: AWS_REGION
                  value: eu-west-1
                - name: AWS_ACCESS_KEY_ID
                  value: <key>
                - name: AWS_SECRET_ACCESS_KEY
                  value: <key>

```

then i create job to perform cronjob instantly
```bash
sudo kubectl create job --from=cronjob/cron-ecr-credentials-helper ecr2
```

But the container does not want to finish its job

```bash
$ sudo kubectl get jobs
NAME   COMPLETIONS   DURATION   AGE
ecr    0/1           5m52s      5m52s
ecr2   0/1           3m9s       3m9s
```

All i get is
```bash
$ sudo kubectl logs ecr-ql9fw
Running at 2020-06-15 18:16:25.248476379 +0000 UTC
```

This behavior is present from about 2 hours (only one run was successful), however when I was trying to run the container few hours ago it finished its job correctly in like 5 seconds.

I guess it may be related to the lack of checking if AWS API is up (I am going to investigate it more soon)
